version: '1.0.{build}'
configuration: Release
image: Visual Studio 2017
branches:
  only: 
    - develop
clone_folder: C:\Users\user\Source\Repos\MSolve
shallow_clone: true
environment:
  SonarToken:
    secure: 3lJulb34VViwfO7lW6zJQQBm+3ke5nuvaZZyDMEF7YsaHq012AFg9A1xZ43iqg2D
cache:
  - packages
install:
  - dotnet restore --packages packages 
before_build:
  - nuget restore
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"ISAAR.MSolve" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=SonarToken"
  - msbuild "ISAAR.MSolve.sln"
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=SonarToken"  
build:
  project: ISAAR.MSolve.sln
  
  
