version: '1.0.{build}'
configuration: Release
image: Visual Studio 2017
branches:
  only: 
    - develop
clone_folder: C:\Users\user\Source\Repos\MSolve
shallow_clone: true
environment:
  CODECOV_TOKEN:
    secure: X4e0xZjF4hpFxNTvKGC9QhyjnCML5BixbxDNytIGWNvBNlHGf+YKIa2fbofbRHG1
cache:
  - packages
install:
  - dotnet restore --packages packages 
before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov
build:
  project: ISAAR.MSolve.sln
  verbosity: minimal

test_script:
- ps: >-
    $opencover = (Resolve-Path packages/opencover/*/tools/opencover.console.exe).ToString()
    & $opencover -register:user -target:"dotnet.exe" -targetargs:"test ISAAR.MSolve.Tests --configuration Debug /p:DebugType=Full" -output:opencoverCoverage.xml -oldStyle -excludebyattribute:*.ExcludeFromCodeCoverage*^ -filter:"+[*]* -[ISAAR.MSolve.Tests*]*" -hideskipped:all
    Push-AppveyorArtifact opencoverCoverage.xml
    
after_test:
- ps: >-
    $codecov = (Resolve-Path packages/codecov/*/tools/codecov.exe).ToString()
    & $codecov -f "opencoverCoverage.xml" -t $env:CODECOV_TOKEN
  
  
