version: '1.0.{build}'
configuration: Release
image: Visual Studio 2017
branches:
  only: 
    - develop
clone_folder: C:\Users\user\Source\Repos\MSolve
shallow_clone: true
environment:
  SonarCloudToken:
    secure: pxDIx52G3LOm7+SVLZ2sk99gtSs8zqUDNbeVxRSwI7N8qwGJpjhUr7s4AuIWA/Bx
cache:
  - packages
install:
  - dotnet restore --packages packages 
before_build:
  - nuget restore
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"ISAAR.MSolve" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=SonarCloudToken"
  - msbuild "ISAAR.MSolve.sln"
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=SonarCloudToken"  
build:
  project: ISAAR.MSolve.sln
  
  
